[package]
name = "service-example"
edition = "2024"

[dependencies]
anyhow = "1"
async-trait = "0.1"
axum = "0.8.6"
notmad = "0.8.1"
tokio = "1"
tokio-util = "0.7.17"
tracing = "0.1"
tracing-subscriber = { version = "0.2", features = ["env-filter"] }
