[package]
name = "forest-grpc-interface"
edition = "2024"
version.workspace = true

[dependencies]
bytes.workspace = true
prost.workspace = true
prost-types.workspace = true
tonic.workspace = true
tonic-prost.workspace = true
